# Generated by Django 3.0.2 on 2020-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='add2',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='fname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
